<?php

/**
 * @file
 * Sophron Guesser - Replaces Drupal core MIME type guesser with Sophron.
 */

use Drupal\file\FileInterface;
use Symfony\Component\Mime\MimeTypes;

/**
 * Implements hook_help().
 */
function sophron_guesser_file_validate(FileInterface $file) {
  $symfonyMimeTypes =  new MimeTypes();

  //throw new \RuntimeException($path);
  $realType = $symfonyMimeTypes->guessMimeType($file->getFileUri());

//  dump($file);
  $errors = [];
  $errors = $file->getFilename() . ' - ' . $file->getFileUri() . ' - ' . $file->getMimeType() . ' - ' . $realType;
//  throw new \RuntimeException(var_export($file, true));
/*  if (!$file->getFilename()) {
    $errors[] = t("The file's name is empty. Please give a name to the file.");
  }
  if (strlen($file->getFilename()) > 255) {
   $errors[] = t("The file's name exceeds the 255 characters limit. Please rename the file and try again.");
 }*/

  return $errors;
}
