uaparser.settings:
  type: config_object
  label: 'ua-parser settings'
  mapping:
    enable_automatic_updates:
      type: boolean
      label: 'Enable Automatic Updates'
    automatic_updates_timer:
      type: string
      label: 'Automatic Updates Timer'
    regexes_file_location:
      type: string
      label: 'Location of the regexes file'
