sophron.settings:
  type: config_object
  label: 'Sophron settings'
  mapping:
    map_class:
      type: string
      label: 'The map class to use by default'
    map_commands:
      type: sequence
      label: 'A sequence of mapping commands'
      sequence:
        type: sophron.mapping_command
